language: python
sudo: false
python:
    - "2.7"
    - "3.5"
    - "3.6"

matrix:
  fast_finish: True

before_install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Install dependencies
  - conda create -n test-env python=$TRAVIS_PYTHON_VERSION
  - conda env update -n test-env -f requirements.txt
  - source activate test-env

install:
  - python setup.py develop --no-deps

script:
    - flake8 conda_shell tests setup.py
    - pytest --cov=conda_shell --cov-report term-missing
