language: python

matrix:
  fast_finish: True
  include:
    - os: linux
      sudo: false
      python: 2.7
      env: PYTHON_VERSION=2.7
    - os: linux
      sudo: false
      python: 3.5
      env: PYTHON_VERSION=3.5
    - os: linux
      sudo: false
      python: 3.6
      env: PYTHON_VERSION=3.6
    - os: osx
      language: generic
      env: PYTHON_VERSION=2.7
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.5
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.6

before_install:
  # Install conda
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget http://repo.continuum.io/miniconda/Miniconda$(echo $PYTHON_VERSION | cut -d. -f1)-latest-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda$(echo $PYTHON_VERSION | cut -d. -f1)-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Conda's version of Python needs to reflect conda-shell's
  # due to code/library reuse:
  - conda install -n root python=${PYTHON_VERSION}

  # Install dependencies
  - conda create -n test-env python=${PYTHON_VERSION}
  - conda env update -n test-env -f environment.yml
  - source activate test-env

install:
  - python setup.py develop --no-deps

script:
  - flake8 setup.py conda_shell
  - pytest --cov=conda_shell --cov-report term-missing tests

after_success:
  - coveralls
