{% set data = load_setup_py_data() %}

package:
  name: conda_shell
  version: {{ data.get('version') }}

source:
  path: ..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0)|int }}

requirements:
  build:
    - python
    - setuptools
    - pyyaml
    - six

  run:
    - python
    - six
    - mock  # [py2k]

test:
  requires:
    - pytest
    - pytest-cov

  commands:
    - pytest --cov=conda_shell --cov-report term-missing -x $SP_DIR/tests  # [unix]
    - pytest --cov=conda_shell --cov-report term-missing %SP_DIR%/tests  # [win]
    - which conda-shell

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}

extra:
  maintainers:
    - Greg Brener (gregshipssoftware [at] gmail [dot] com)
