{% set data = load_setup_py_data() %}

package:
  name: conda-shell
  version: {{ data.get('version') }}

source:
  path: ..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0)|int }}

requirements:
  build:
    - python
    - setuptools

  run:
    - python

about:
  home: http://github.com/gbrener/conda-shell
  license: BSD

test:
  command:
    - which conda-shell

extra:
  maintainers:
    - Greg Brener (gregshipssoftware [at] gmail [dot] com)
